# Generated by Django 4.1.5 on 2023-01-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Darowizny'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
